name = "QuantumGraphs.jl"
uuid = "4872dfc6-05e2-49b0-9126-c2c3149bf648"
authors = ["Gavin <gavin.rockwood@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
